version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_rbac
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./db.sqlite3
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload